AppBiblioteca/urls.py
from django.urls import path
from .views import PaginaInicioView, ListarLibrosView, ListarAutoresView, DisponibilidadYAlquilerView, AboutView
#Creo las urls necesarias para poder navegar en las paginas.
urlpatterns = [
    path('', PaginaInicioView.as_view(), name='pagina_inicio'),  
    path('libros/', ListarLibrosView.as_view(), name='listar_libros'),
    path('autores/', ListarAutoresView.as_view(), name='listar_autores'),
    path('disponibilidad_y_alquiler/', DisponibilidadYAlquilerView.as_view(), name='disponibilidad_y_alquiler'),
    path('about/', AboutView.as_view(), name='about'),
]

TercerEntrega/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("AppBiblioteca.urls")),
    path('users/', include('users.urls')),
]

# Configuración para servir archivos multimedia 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
# users/urls.py
from django.urls import path
from .views import SignUpView, CustomLoginView, CustomLogoutView, ProfileUpdateView, CustomPasswordChangeView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
]

AppBiblioteca/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings 

# Definición del modelo Autor.
class Autor(models.Model):
    # Campo para el nombre del autor.
    nombre = models.CharField(max_length=100)
    # Campo para el apellido del autor.
    apellido = models.CharField(max_length=100)
    # Campo para la fecha de nacimiento del autor.
    fecha_nacimiento = models.DateField()
    # Campo para la nacionalidad del autor.
    nacionalidad = models.CharField(max_length=100)
    # Método para representar el autor como una cadena.
    def __str__(self):
        return f"{self.nombre} {self.apellido}"
# Definición del modelo Libro.
class Libro(models.Model):
    # Campo para el título del libro.
    titulo = models.CharField(max_length=200)
    # Campo para la relación con el autor (clave foránea).
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE )
    # Campo para la fecha de publicación del libro.
    fecha_publicacion = models.DateField() 
    # Campo para el ISBN del libro (debe ser único).
    isbn = models.CharField(max_length=13, unique=True )
    # Campo para indicar si el libro está disponible.
    disponible = models.BooleanField(default=True) 
    # Campo para la portada del libro (opcional).
    portada = models.ImageField(upload_to='portadas/', null=True, blank=True)
    # Método para representar el libro como una cadena.
    def __str__(self):
        return self.titulo
# Definición del modelo Alquiler.
class Alquiler(models.Model):
    # Campo para la relación con el libro (clave foránea).
    libro = models.ForeignKey(Libro, on_delete=models.CASCADE)
    # Campo para la relación con el usuario que alquila (clave foránea).
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    # Campo para la fecha y hora del alquiler.
    fecha_alquiler = models.DateTimeField(default=timezone.now)
    # Método para representar el alquiler como una cadena.
    def __str__(self):
        return f"Alquiler de {self.libro.titulo}"
    # Método para guardar el alquiler en la base de datos.
    def save(self, *args, **kwargs):
        # Verifica si es una nueva instancia del alquiler (sin PK).
        is_new_instance = self.pk is None
        # Llama al método save de la clase base.
        super().save(*args, **kwargs)
        # Si es una nueva instancia, marca el libro como no disponible.
        if is_new_instance:
            self.libro.disponible = False
            self.libro.save()
        else:
            # Si no es una nueva instancia, marca el libro como disponible si es necesario.
            if self.libro.disponible:
                self.libro.disponible = True
                self.libro.save()

AppBiblioteca/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Autor, Libro, Alquiler
from .forms import AutorForm, LibroForm, AlquilerForm, DevolucionForm, BusquedaLibroForm, LibroFilterForm
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView, TemplateView
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin

# Vista para la página de inicio con un formulario de búsqueda de libros.
class PaginaInicioView(FormView):
    # Plantilla a usar para esta vista.
    template_name = 'AppBiblioteca/inicio.html'
    # Formulario usado en esta vista.
    form_class = BusquedaLibroForm
    # Método llamado cuando el formulario es válido.
    def form_valid(self, form):
        # Obtiene el título del libro del formulario.
        titulo = form.cleaned_data.get('titulo')
        libros = None
        # Si hay un título, busca libros que contengan ese título.
        if titulo:
            libros = Libro.objects.filter(titulo__icontains=titulo)
        # Renderiza la respuesta con el contexto adecuado.
        return self.render_to_response(self.get_context_data(form=form, libros=libros))
# Vista para listar libros y agregar un nuevo libro.
class ListarLibrosView(LoginRequiredMixin, ListView, FormView):
    # Modelo asociado con esta vista.
    model = Libro
    # Plantilla a usar para esta vista.
    template_name = 'AppBiblioteca/listar_libros.html'
    # Formulario usado en esta vista.
    form_class = LibroForm
    # URL de éxito para redireccionar después de una acción exitosa.
    success_url = reverse_lazy('listar_libros')
    # Método para obtener el contexto de la vista.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Incluye la lista de libros en el contexto.
        context['libros'] = self.get_queryset()
        # Incluye el formulario en el contexto.
        context['form'] = self.get_form()
        return context
    # Método para manejar las solicitudes POST.
    def post(self, request, *args, **kwargs):
        # Obtiene el formulario con los datos del POST.
        form = self.get_form()
        # Verifica si el formulario es válido.
        if form.is_valid():
            return self.form_valid(form)
        else:
            # Redirige con un mensaje de error si el formulario no es válido.
            messages.error(self.request, "Los datos ingresados son incorrectos. Por favor, corríjalos e intente nuevamente.")
            return redirect(self.success_url)
    # Método llamado cuando el formulario es válido.
    def form_valid(self, form):
        # Guarda el formulario y redirige a la URL de éxito.
        form.save()
        messages.success(self.request, "Libro guardado exitosamente.")
        return redirect(self.success_url)
# Vista para listar autores y agregar un nuevo autor.
class ListarAutoresView(LoginRequiredMixin, ListView, FormMixin):
    # Modelo asociado con esta vista.
    model = Autor
    # Plantilla a usar para esta vista.
    template_name = 'AppBiblioteca/listar_autores.html'
    # Nombre del contexto para los autores.
    context_object_name = 'autores'
    # Formulario usado en esta vista.
    form_class = AutorForm
    # URL de éxito para redireccionar después de una acción exitosa.
    success_url = reverse_lazy('listar_autores')
    # Método para obtener el contexto de la vista.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Incluye el formulario en el contexto.
        context['form'] = self.get_form()
        return context
    # Método para manejar las solicitudes POST.
    def post(self, request, *args, **kwargs):
        # Obtiene el formulario con los datos del POST.
        form = self.get_form()
        # Verifica si el formulario es válido.
        if form.is_valid():
            return self.form_valid(form)
        else:
            # Redirige con un mensaje de error si el formulario no es válido.
            messages.error(self.request, "Los datos ingresados son incorrectos. Por favor, corríjalos e intente nuevamente.")
            return redirect(self.success_url)
    # Método llamado cuando el formulario es válido.
    def form_valid(self, form):
        # Guarda el formulario y redirige a la URL de éxito.
        form.save()
        messages.success(self.request, "Autor guardado exitosamente.")
        return redirect(self.success_url)
# Vista para gestionar la disponibilidad y alquiler de libros.
class DisponibilidadYAlquilerView(LoginRequiredMixin, TemplateView):
    # Plantilla a usar para esta vista.
    template_name = 'AppBiblioteca/disponibilidad_y_alquiler.html'
    # Método para obtener el contexto de la vista.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Obtiene el filtro de disponibilidad del GET request.
        disponibilidad = self.request.GET.get('disponibilidad', '')
        # Filtra los libros según la disponibilidad.
        if disponibilidad == 'disponible':
            context['libros'] = Libro.objects.filter(disponible=True)
        elif disponibilidad == 'no_disponible':
            context['libros'] = Libro.objects.filter(disponible=False)
        else:
            context['libros'] = Libro.objects.all()
        # Obtiene el libro seleccionado si se ha hecho clic en "Ver más".
        libro_id = self.request.GET.get('libro_id')
        if libro_id:
            context['libro_seleccionado'] = get_object_or_404(Libro, id=libro_id)
        # Incluye los formularios de alquiler y devolución en el contexto.
        context['alquiler_form'] = AlquilerForm()
        context['devolucion_form'] = DevolucionForm(current_user=self.request.user)
        context['filter_form'] = LibroFilterForm(initial={'disponibilidad': disponibilidad})
        return context
    # Método para manejar las solicitudes POST.
    def post(self, request, *args, **kwargs):
        # Manejo del formulario de alquiler.
        if 'alquiler_form' in request.POST:
            alquiler_form = AlquilerForm(request.POST)
            if alquiler_form.is_valid():
                alquiler = alquiler_form.save(commit=False)
                alquiler.usuario = request.user
                alquiler.libro.disponible = False
                alquiler.libro.save()
                alquiler.save()
                messages.success(request, f"Libro '{alquiler.libro}' alquilado exitosamente.")
                return redirect('disponibilidad_y_alquiler')
            else:
                messages.error(request, "Error al alquilar el libro.")
        # Manejo del formulario de devolución.
        elif 'devolucion_form' in request.POST:
            devolucion_form = DevolucionForm(request.POST, current_user=request.user)
            if devolucion_form.is_valid():
                libro = devolucion_form.cleaned_data['libro']
                try:
                    alquiler = Alquiler.objects.get(libro=libro, usuario=request.user)
                    libro.disponible = True
                    libro.save()
                    alquiler.delete()
                    messages.success(request, "Libro devuelto exitosamente.")
                except Alquiler.DoesNotExist:
                    messages.error(request, "No se encontró un alquiler para el libro seleccionado o no es el libro alquilado por usted.")
                return redirect('disponibilidad_y_alquiler')
            else:
                messages.error(request, "Error al devolver el libro.")
        # Redibuja la vista con el contexto actual.
        context = self.get_context_data()
        return self.render_to_response(context)
# Vista para la página "Sobre nosotros".
class AboutView(TemplateView):
    # Plantilla a usar para esta vista.
    template_name = 'AppBiblioteca/about.html'

AppBiblioteca/templates/AppBiblioteca/Base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Biblioteca Virtual</title>
    <link rel="icon" type="image/x-icon" href="{% static 'AppBiblioteca/assets/favicon.ico' %}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'AppBiblioteca/css/styles.css' %}" rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="{% url 'pagina_inicio' %}">Biblioteca Virtual</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'pagina_inicio' %}">Inicio</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'listar_libros' %}">Libros</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'listar_autores' %}">Autores</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'disponibilidad_y_alquiler' %}">Disponibilidad y Alquiler</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'about' %}">About</a></li>  <!-- Botón "About" -->
                    <!-- Menú de autenticación colapsable -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="authDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {% if user.is_authenticated %}
                                {% if user.avatar %}
                                    <img src="{{ user.avatar.url }}" alt="Avatar de {{ user.username }}" class="rounded-circle" style="width: 30px; height: 30px; object-fit: cover; margin-right: 8px;">
                                {% endif %}
                                Mi Perfil
                            {% else %}
                                Ingresar
                            {% endif %}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="authDropdown">
                            {% if user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'profile' %}">Mi Perfil</a></li>
                                <li>
                                    <!-- Formulario de Logout -->
                                    <form action="{% url 'logout' %}" method="post" class="dropdown-item">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-link">Cerrar Sesión</button>
                                    </form>
                                </li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url 'signup' %}">Registrarse</a></li>
                                <li><a class="dropdown-item" href="{% url 'login' %}">Iniciar Sesión</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Header-->
    <header class="masthead" style="background-image: url('{% static 'AppBiblioteca/assets/img/home-bg.jpg' %}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Bienvenidos</h1>
                        <span class="subheading">Nuestra Biblioteca</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    {% block ContenidoQueCambia %}
    {% endblock %}

    <!-- Footer-->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'AppBiblioteca/js/scripts.js' %}"></script>
</body>
</html>

AppBiblioteca/templates/AppBiblioteca/about.html
{% extends 'AppBiblioteca/base.html' %}
{% load static %}
{% block ContenidoQueCambia %}
  <div class="container mt-4">
    <div class="row">
      <!-- Contenedor Izquierdo -->
      <div class="col-md-4">
        <div class="card mb-4 text-center" style="background-color: #f8f9fa;"> <!-- Fondo gris claro -->
          <!-- Imagen redonda más grande y centrada -->
          <img src="{% static 'AppBiblioteca/assets/img/franco.jpg' %}" 
               class="card-img-top rounded-circle mx-auto d-block mt-4" 
               alt="Tu foto" style="width: 200px; height: 200px; object-fit: cover;">
          <div class="card-body">
            <h5 class="card-title">Franco Sposetti</h5>
            <p class="card-text">Python developear junior</p>
            <div class="d-flex justify-content-center">
              <a href="https://github.com/FrancoSposetti" target="_blank" class="btn btn-link me-2" style="font-size: 1.5rem;">
                <i class="fab fa-github"></i>
              </a>
              <a href="https://www.linkedin.com/in/franco-sposetti-599001206/" target="_blank" class="btn btn-link" style="font-size: 1.5rem;">
                <i class="fab fa-linkedin"></i>
              </a>
            </div>
          </div>
        </div>
      </div>

      <!-- Contenido Principal -->
      <div class="col-md-8">
        <h2>Acerca de Mi</h2>
        <p>
          Bienvenido a nuestra Biblioteca Virtual. Nos apasiona conectar a las personas con el mundo de la literatura.
          Esta plataforma fue creada con el propósito de facilitar el acceso a libros y recursos educativos para todos.
        </p>
        <p>
          Mi nombre es Franco Sposetti , soy estudiante del leguanje de programacion Python y del framework Django,gracias por visitar mi pagina web y no dejes de seguirme en mis redes sociales! 
        </p>
        <p>
          Gracias por ser parte de nuestra comunidad. ¡Esperamos que disfrutes de tu tiempo aquí!
        </p>
      </div>
    </div>
  </div>
{% endblock %}

AppBiblioteca/templates/AppBiblioteca/disponibilidad_y_alquiler.html
{% extends 'AppBiblioteca/base.html' %}

{% block ContenidoQueCambia %}
<div class="container mt-4">
    <h2>Disponibilidad y Alquiler de Libros</h2>
    
    <!-- Formulario de filtro -->
    <div class="row mb-4">
        <div class="col-md-4">
            <form method="get" action="{% url 'disponibilidad_y_alquiler' %}" class="mb-3">
                <div class="form-group">
                    {% comment %} <label for="disponibilidad">Filtrar por Disponibilidad:</label> {% endcomment %}
                    {{ filter_form.disponibilidad.label_tag }}
                    {{ filter_form.disponibilidad }}
                </div>
                <button type="submit" class="btn btn-primary">Filtrar</button>
            </form>
        </div>
    </div>

    <!-- Listado de libros -->
    <h3>Libros</h3>
    <ul class="list-group mb-4">
        {% for libro in libros %}
            <li class="list-group-item">
                {{ libro.titulo }} - {% if libro.disponible %} Disponible {% else %} No Disponible {% endif %}
                <a href="?libro_id={{ libro.id }}&disponibilidad={{ filter_form.initial.disponibilidad }}" class="btn btn-info btn-sm float-right">Ver más</a>
            </li>
        {% empty %}
            <li class="list-group-item">No hay libros disponibles según el filtro aplicado.</li>
        {% endfor %}
    </ul>

    <!-- Detalles del libro seleccionado -->
    {% if libro_seleccionado %}
        <h3>Detalles del libro seleccionado</h3>
        <p><strong>Título:</strong> {{ libro_seleccionado.titulo }}</p>
        <p><strong>Autor:</strong> {{ libro_seleccionado.autor }}</p>
        <p><strong>Fecha de Publicación:</strong> {{ libro_seleccionado.fecha_publicacion }}</p>
        <p><strong>ISBN:</strong> {{ libro_seleccionado.isbn }}</p>
        <p><strong>Disponible:</strong> {% if libro_seleccionado.disponible %} Sí {% else %} No {% endif %}</p>
        {% if libro_seleccionado.portada %}
            <p><strong>Portada:</strong></p>
            <img src="{{ libro_seleccionado.portada.url }}" alt="Portada del libro" class="img-fluid">
        {% endif %}
    {% endif %}

    <!-- Formulario de alquiler -->
    <h3>Alquilar Libro</h3>
    <form method="post" class="mb-4">
        {% csrf_token %}
        {{ alquiler_form.as_p }}
        <button type="submit" name="alquiler_form" class="btn btn-success">Alquilar</button>
    </form>

    <!-- Formulario de devolución -->
    <h3>Devolver Libro</h3>
    <form method="post">
        {% csrf_token %}
        {{ devolucion_form.as_p }}
        <button type="submit" name="devolucion_form" class="btn btn-warning">Devolver</button>
    </form>
</div>
{% endblock %}

AppBiblioteca/templates/AppBiblioteca/inicio.html
{% extends 'AppBiblioteca/base.html' %}

{% block ContenidoQueCambia %}
<h1>Página de Inicio</h1>

<!-- Formulario de búsqueda -->
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Buscar</button>
</form>

<!-- Mostrar resultados de búsqueda -->
{% if libros %}
    <h2>Resultados de búsqueda:</h2>
    <ul>
        {% for libro in libros %}
            <li>
                <!-- Mostrar la imagen de la portada si existe -->
                {% if libro.portada %}
                    <img src="{{ libro.portada.url }}" alt="Portada de {{ libro.titulo }}" width="100" style="vertical-align:middle; margin-right:10px;">
                {% endif %}
                <!-- Mostrar detalles del libro -->
                {{ libro.titulo }} - {{ libro.autor }} - {{ libro.fecha_publicacion }} - 
                {% if libro.disponible %}
                    Disponible
                {% else %}
                    No disponible
                {% endif %}
            </li>
        {% empty %}
            <li>No se encontraron libros.</li>
        {% endfor %}
    </ul>
{% endif %}

{% endblock %}

AppBiblioteca/templates/AppBiblioteca/listar_autores.html
{% extends 'AppBiblioteca/base.html' %}

{% block ContenidoQueCambia %}

<h2>Autores</h2>
<!-- Mostrar mensajes de error o éxito -->
{% if messages %}
    <div class="alert alert-info">
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    </div>
{% endif %}
<ul>
    {% for autor in autores %}
        <li>{{ autor.nombre }} {{ autor.apellido }}</li>
        <ul>
            {% for libro in autor.libro_set.all %}
                <li>{{ libro.titulo }}</li>
            {% endfor %}
        </ul>
    {% endfor %}
</ul>
<h3>Agregar Autor</h3>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Guardar</button>
</form>

{% endblock %}

AppBiblioteca/templates/AppBiblioteca/listar_libros.html
{% extends 'AppBiblioteca/base.html' %}

{% block ContenidoQueCambia %}

<h1>Página de Libros</h1>
<!-- Mostrar mensajes de error o éxito -->
{% if messages %}
    <div class="alert alert-info">
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    </div>
{% endif %}
<!-- Formulario para agregar un nuevo libro -->
<h3>Agregar Libro</h3>
<form method="post" enctype="multipart/form-data">  <!-- Agregar enctype="multipart/form-data" -->
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Guardar</button>
</form>

{% endblock %}